# Generated by Django 4.2.9 on 2026-05-19 15:52

import apps.accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_profile_avatar_alter_user_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to=apps.accounts.models.banner_upload_path),
        ),
    ]
